### ISSUE TITLE
Plexure Api Key "You do not have permission to view this directory or page."

### ISSUE THREAD

**Issue by Wafend** [giacomoferretti/mcdapi#2]
Hey,
I`ve tried your plexure api generator in coupons.py but i get "You do not have permission to view this directory or page." when i try to use it in a request. Also is the parameter "password" simply the password of the account?

**Comment by giacomoferretti** [comment]
What was the problem? Can you give me more details?

**Comment by Wafend** [comment]
Everything is working fine thanks.
i just forget to gen the vmob uid
Thanks for your work :D

Am Mo., 5. Aug. 2019 um 14:23 Uhr schrieb Giacomo Ferretti <
notifications@github.com>:

**Comment by giacomoferretti** [comment]
No problem!
You can donate if this project was helpful to you :)
